### ISSUE TITLE
[Question] How to use/is it usable?

### ISSUE THREAD

**Issue by TsundereBug** [jacobly0/llvm-z80#6]
And how do I access the screen on my ti-84+ce with this?

**Comment by jacobly0** [comment]
It's barely usable but you can try it out on the [Project Builder](http://tiplanet.org/pb/) by using the Build &rightarrow; Build from LLVM ASM option or you can compile it yourself by `git clone`ing this repo, checking `git log` for the correct llvm revision to use, `svn checkout --force --revision <rev> <repo>` both llvm and clang, and building llvm with `LLVM_EXPERIMENTAL_TARGETS_TO_BUILD=Z80`.

And while utterly unrelated to a compiler, you can access the screen of a ti-84+ce in the default mode with a simple `#define screen (*(unsigned short (*)[240][320])0xD40000)`.

**Comment by TsundereBug** [comment]
I'll actually be using Crystal to do my program writing, so that would be
`SCREEN = pointerof(0xD40000)`

     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|
